[settings]
experimental        = true
npm.package_manager = "pnpm"

[settings.github]
use_git_credentials = true

[tools]

# tool
"aqua:anthropics/claude-code" = "2.1.138"
"aqua:j178/prek"              = "0.4.3"
"aqua:jqlang/jq"              = "1.8.1"
"aqua:nektos/act"             = "0.2.88"

# lint/formatter
"aqua:biomejs/biome"                             = "2.4.15"
"aqua:editorconfig-checker/editorconfig-checker" = "3.6.1"
"aqua:google/yamlfmt"                            = "0.21.0"
"aqua:koalaman/shellcheck"                       = "0.11.0"
"aqua:mvdan/sh"                                  = "3.13.1"
"aqua:rhysd/actionlint"                          = "1.7.12"
"aqua:tamasfe/taplo"                             = "0.10.0"

# CI/checker
"aqua:gitleaks/gitleaks"      = "8.30.1"
"aqua:suzuki-shunsuke/pinact" = "4.0.0"
"aqua:zizmorcore/zizmor"      = "1.25.2"

[hooks]
postinstall = "mise generate git-pre-commit -w --task=pre-commit"

[tasks.pre-commit]
run = "prek run"
