default_stages: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets
        entry: mise exec -- gitleaks protect --verbose --redact --staged
        language: system
        pass_filenames: false

      - id: editorconfig-check
        name: editorconfig check
        entry: mise exec -- ec
        language: system
        pass_filenames: true
        types: [text]

      - id: taplo-lint
        name: taplo lint
        entry: mise exec -- taplo lint
        language: system
        pass_filenames: true
        files: \.(toml)$

      - id: taplo-format
        name: taplo format
        entry: mise exec -- taplo format
        language: system
        pass_filenames: true
        files: \.(toml)$
        require_serial: true

      - id: yaml-format
        name: yaml format
        entry: mise exec -- yamlfmt
        language: system
        pass_filenames: true
        files: \.(yaml|yml)$
        require_serial: true

      - id: shell-lint
        name: shell lint
        entry: mise exec -- shellcheck
        language: system
        pass_filenames: true
        files: \.(sh)$

      - id: shell-format
        name: shell format
        entry: mise exec -- shfmt -ci
        language: system
        pass_filenames: true
        files: \.(sh)$
        require_serial: true

      - id: json-lint
        name: json lint
        entry: mise exec -- biome lint
        language: system
        pass_filenames: true
        files: \.(json|jsonc)$

      - id: json-format
        name: json format
        entry: mise exec -- biome format
        language: system
        pass_filenames: true
        files: \.(json|jsonc)$
        require_serial: true
